CREATE TABLE IF NOT EXISTS AUDIOS (
    FILE_HASH CHAR(64) PRIMARY KEY
    , AUDIO_TITLE VARCHAR(256)
    , ALBUM_NAME VARCHAR(256)
    , ARTIST_NAME VARCHAR(256)
    , TRACK_NUM INT(8)
    , RELEASE_YEAR INT(16)
    , AUDIO_LENGTH_SECONDS INT(64)
    , AUDIO_PATH VARCHAR(256) -- Windows path limit.
    , IMG_PATH VARCHAR(256) -- Windows path limit.
) WITHOUT ROWID;
