WITH MATCHING_PLAYLISTS AS (
    SELECT PLAYLISTS.FILE_HASH
    FROM PLAYLISTS
    WHERE PLAYLISTS.PLAYLIST_NAME = :playlist_name
)

SELECT
    SONGS.FILE_HASH
    , SONGS.SONG_TITLE
    , SONGS.ALBUM_NAME
    , SONGS.ARTIST_NAME
    , SONGS.TRACK_NUM
    , SONGS.RELEASE_YEAR
    , SONGS.SONG_LENGTH_SECONDS
    , SONGS.SONG_PATH
    , SONGS.IMG_PATH
FROM MATCHING_PLAYLISTS
INNER JOIN SONGS
    ON
        MATCHING_PLAYLISTS.FILE_HASH = SONGS.FILE_HASH;
