CREATE TABLE IF NOT EXISTS PLAYLISTS (
    SONG_HASH CHAR(64)
    , PLAYLIST_TITLE VARCHAR(256)
    , IMG_PATH VARCHAR(256) -- Windows path limit.
    , PRIMARY KEY (PLAYLIST_TITLE, SONG_HASH)
) WITHOUT ROWID;
